name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
      
      - name: Remove node_modules directory
        run: rm -rf node_modules

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git checkout --orphan gh-pages
          git rm -rf .
          mv example/dist/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"
          git push --force origin gh-pages
